##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#   2024-04-27 - Added env file inclusion. 
#                Added way to overide: build directory, target name and optimisation.
#                Added GCC_PATH by env file to not make the makefile machine dependent.
#                Currently folder structure in build directory is preserved
#                Switching of debug/release build output folder now happens based on debug flag
#   2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

######################################
# Target
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= stm32f407g_MES_Minisynth

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.:
# make -f STM32Make.make -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -O2

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/ADSR_envelope.c \
Core/Src/LCDController.c \
Core/Src/MIDI_application.c \
Core/Src/MIDI_event.c \
Core/Src/SEGGER_RTT.c \
Core/Src/SEGGER_RTT_printf.c \
Core/Src/UI_LCD.c \
Core/Src/UI_hardware.c \
Core/Src/adc.c \
Core/Src/audio.c \
Core/Src/bitcrusher.c \
Core/Src/console.c \
Core/Src/consoleCommands.c \
Core/Src/consoleIo.c \
Core/Src/dma.c \
Core/Src/filters.c \
Core/Src/flanger.c \
Core/Src/gpio.c \
Core/Src/helper_functions.c \
Core/Src/i2c.c \
Core/Src/i2s.c \
Core/Src/ladder_filter.c \
Core/Src/lut_tan.c \
Core/Src/main.c \
Core/Src/oscillators.c \
Core/Src/spi.c \
Core/Src/stereo_delay.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/system_stm32f4xx.c \
Core/Src/tim.c \
Core/Src/usbh_MIDI.c \
Core/Src/usbh_conf.c \
Drivers/BSP/Components/cs43l22/cs43l22.c \
Drivers/BSP/Components/lis302dl/lis302dl.c \
Drivers/BSP/Components/lis3dsh/lis3dsh.c \
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery.c \
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_accelerometer.c \
Drivers/BSP/STM32F4-Discovery/stm32f4_discovery_audio.c \
Drivers/ST7789V/fonts.c \
Drivers/ST7789V/st7789v.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_alpha16.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_argb.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_chroma_keyed.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_indexed16.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb.c \
Drivers/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb565a8.c \
Drivers/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_12_compr_az.c.c \
Drivers/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_16_compr_az.c.c \
Drivers/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_28_compr_az.c.c \
Drivers/lvgl/demos/benchmark/lv_demo_benchmark.c \
Drivers/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_logo.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
Drivers/lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
Drivers/lvgl/demos/music/lv_demo_music.c \
Drivers/lvgl/demos/music/lv_demo_music_list.c \
Drivers/lvgl/demos/music/lv_demo_music_main.c \
Drivers/lvgl/demos/stress/lv_demo_stress.c \
Drivers/lvgl/demos/widgets/assets/img_clothes.c \
Drivers/lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
Drivers/lvgl/demos/widgets/assets/img_lvgl_logo.c \
Drivers/lvgl/demos/widgets/lv_demo_widgets.c \
Drivers/lvgl/env_support/rt-thread/lv_rt_thread_port.c \
Drivers/lvgl/env_support/rt-thread/squareline/lv_ui_entry.c \
Drivers/lvgl/src/core/lv_disp.c \
Drivers/lvgl/src/core/lv_event.c \
Drivers/lvgl/src/core/lv_group.c \
Drivers/lvgl/src/core/lv_indev.c \
Drivers/lvgl/src/core/lv_indev_scroll.c \
Drivers/lvgl/src/core/lv_obj.c \
Drivers/lvgl/src/core/lv_obj_class.c \
Drivers/lvgl/src/core/lv_obj_draw.c \
Drivers/lvgl/src/core/lv_obj_pos.c \
Drivers/lvgl/src/core/lv_obj_scroll.c \
Drivers/lvgl/src/core/lv_obj_style.c \
Drivers/lvgl/src/core/lv_obj_style_gen.c \
Drivers/lvgl/src/core/lv_obj_tree.c \
Drivers/lvgl/src/core/lv_refr.c \
Drivers/lvgl/src/core/lv_theme.c \
Drivers/lvgl/src/draw/arm2d/lv_gpu_arm2d.c \
Drivers/lvgl/src/draw/lv_draw.c \
Drivers/lvgl/src/draw/lv_draw_arc.c \
Drivers/lvgl/src/draw/lv_draw_img.c \
Drivers/lvgl/src/draw/lv_draw_label.c \
Drivers/lvgl/src/draw/lv_draw_layer.c \
Drivers/lvgl/src/draw/lv_draw_line.c \
Drivers/lvgl/src/draw/lv_draw_mask.c \
Drivers/lvgl/src/draw/lv_draw_rect.c \
Drivers/lvgl/src/draw/lv_draw_transform.c \
Drivers/lvgl/src/draw/lv_draw_triangle.c \
Drivers/lvgl/src/draw/lv_img_buf.c \
Drivers/lvgl/src/draw/lv_img_cache.c \
Drivers/lvgl/src/draw/lv_img_decoder.c \
Drivers/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
Drivers/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c \
Drivers/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c \
Drivers/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
Drivers/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
Drivers/lvgl/src/draw/renesas/lv_gpu_d2_draw_label.c \
Drivers/lvgl/src/draw/renesas/lv_gpu_d2_ra6m3.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_arc.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_bg.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_composite.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_img.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_label.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_layer.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_line.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_mask.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_rect.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c \
Drivers/lvgl/src/draw/sdl/lv_draw_sdl_utils.c \
Drivers/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_arc.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_blend.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_dither.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_img.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_layer.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_letter.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_line.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_rect.c \
Drivers/lvgl/src/draw/sw/lv_draw_sw_transform.c \
Drivers/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c \
Drivers/lvgl/src/extra/layouts/flex/lv_flex.c \
Drivers/lvgl/src/extra/layouts/grid/lv_grid.c \
Drivers/lvgl/src/extra/libs/bmp/lv_bmp.c \
Drivers/lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c \
Drivers/lvgl/src/extra/libs/freetype/lv_freetype.c \
Drivers/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c \
Drivers/lvgl/src/extra/libs/fsdrv/lv_fs_littlefs.c \
Drivers/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c \
Drivers/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c \
Drivers/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c \
Drivers/lvgl/src/extra/libs/gif/gifdec.c \
Drivers/lvgl/src/extra/libs/gif/lv_gif.c \
Drivers/lvgl/src/extra/libs/png/lodepng.c \
Drivers/lvgl/src/extra/libs/png/lv_png.c \
Drivers/lvgl/src/extra/libs/qrcode/lv_qrcode.c \
Drivers/lvgl/src/extra/libs/qrcode/qrcodegen.c \
Drivers/lvgl/src/extra/libs/rlottie/lv_rlottie.c \
Drivers/lvgl/src/extra/libs/sjpg/lv_sjpg.c \
Drivers/lvgl/src/extra/libs/sjpg/tjpgd.c \
Drivers/lvgl/src/extra/libs/tiny_ttf/lv_tiny_ttf.c \
Drivers/lvgl/src/extra/lv_extra.c \
Drivers/lvgl/src/extra/others/fragment/lv_fragment.c \
Drivers/lvgl/src/extra/others/fragment/lv_fragment_manager.c \
Drivers/lvgl/src/extra/others/gridnav/lv_gridnav.c \
Drivers/lvgl/src/extra/others/ime/lv_ime_pinyin.c \
Drivers/lvgl/src/extra/others/imgfont/lv_imgfont.c \
Drivers/lvgl/src/extra/others/monkey/lv_monkey.c \
Drivers/lvgl/src/extra/others/msg/lv_msg.c \
Drivers/lvgl/src/extra/others/snapshot/lv_snapshot.c \
Drivers/lvgl/src/extra/themes/basic/lv_theme_basic.c \
Drivers/lvgl/src/extra/themes/default/lv_theme_default.c \
Drivers/lvgl/src/extra/themes/mono/lv_theme_mono.c \
Drivers/lvgl/src/extra/widgets/animimg/lv_animimg.c \
Drivers/lvgl/src/extra/widgets/calendar/lv_calendar.c \
Drivers/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
Drivers/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
Drivers/lvgl/src/extra/widgets/chart/lv_chart.c \
Drivers/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
Drivers/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
Drivers/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
Drivers/lvgl/src/extra/widgets/led/lv_led.c \
Drivers/lvgl/src/extra/widgets/list/lv_list.c \
Drivers/lvgl/src/extra/widgets/menu/lv_menu.c \
Drivers/lvgl/src/extra/widgets/meter/lv_meter.c \
Drivers/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
Drivers/lvgl/src/extra/widgets/span/lv_span.c \
Drivers/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
Drivers/lvgl/src/extra/widgets/spinner/lv_spinner.c \
Drivers/lvgl/src/extra/widgets/tabview/lv_tabview.c \
Drivers/lvgl/src/extra/widgets/tileview/lv_tileview.c \
Drivers/lvgl/src/extra/widgets/win/lv_win.c \
Drivers/lvgl/src/font/lv_font.c \
Drivers/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
Drivers/lvgl/src/font/lv_font_fmt_txt.c \
Drivers/lvgl/src/font/lv_font_loader.c \
Drivers/lvgl/src/font/lv_font_montserrat_10.c \
Drivers/lvgl/src/font/lv_font_montserrat_12.c \
Drivers/lvgl/src/font/lv_font_montserrat_12_subpx.c \
Drivers/lvgl/src/font/lv_font_montserrat_14.c \
Drivers/lvgl/src/font/lv_font_montserrat_16.c \
Drivers/lvgl/src/font/lv_font_montserrat_18.c \
Drivers/lvgl/src/font/lv_font_montserrat_20.c \
Drivers/lvgl/src/font/lv_font_montserrat_22.c \
Drivers/lvgl/src/font/lv_font_montserrat_24.c \
Drivers/lvgl/src/font/lv_font_montserrat_26.c \
Drivers/lvgl/src/font/lv_font_montserrat_28.c \
Drivers/lvgl/src/font/lv_font_montserrat_28_compressed.c \
Drivers/lvgl/src/font/lv_font_montserrat_30.c \
Drivers/lvgl/src/font/lv_font_montserrat_32.c \
Drivers/lvgl/src/font/lv_font_montserrat_34.c \
Drivers/lvgl/src/font/lv_font_montserrat_36.c \
Drivers/lvgl/src/font/lv_font_montserrat_38.c \
Drivers/lvgl/src/font/lv_font_montserrat_40.c \
Drivers/lvgl/src/font/lv_font_montserrat_42.c \
Drivers/lvgl/src/font/lv_font_montserrat_44.c \
Drivers/lvgl/src/font/lv_font_montserrat_46.c \
Drivers/lvgl/src/font/lv_font_montserrat_48.c \
Drivers/lvgl/src/font/lv_font_montserrat_8.c \
Drivers/lvgl/src/font/lv_font_simsun_16_cjk.c \
Drivers/lvgl/src/font/lv_font_unscii_16.c \
Drivers/lvgl/src/font/lv_font_unscii_8.c \
Drivers/lvgl/src/hal/lv_hal_disp.c \
Drivers/lvgl/src/hal/lv_hal_indev.c \
Drivers/lvgl/src/hal/lv_hal_tick.c \
Drivers/lvgl/src/misc/lv_anim.c \
Drivers/lvgl/src/misc/lv_anim_timeline.c \
Drivers/lvgl/src/misc/lv_area.c \
Drivers/lvgl/src/misc/lv_async.c \
Drivers/lvgl/src/misc/lv_bidi.c \
Drivers/lvgl/src/misc/lv_color.c \
Drivers/lvgl/src/misc/lv_fs.c \
Drivers/lvgl/src/misc/lv_gc.c \
Drivers/lvgl/src/misc/lv_ll.c \
Drivers/lvgl/src/misc/lv_log.c \
Drivers/lvgl/src/misc/lv_lru.c \
Drivers/lvgl/src/misc/lv_math.c \
Drivers/lvgl/src/misc/lv_mem.c \
Drivers/lvgl/src/misc/lv_printf.c \
Drivers/lvgl/src/misc/lv_style.c \
Drivers/lvgl/src/misc/lv_style_gen.c \
Drivers/lvgl/src/misc/lv_templ.c \
Drivers/lvgl/src/misc/lv_timer.c \
Drivers/lvgl/src/misc/lv_tlsf.c \
Drivers/lvgl/src/misc/lv_txt.c \
Drivers/lvgl/src/misc/lv_txt_ap.c \
Drivers/lvgl/src/misc/lv_utils.c \
Drivers/lvgl/src/widgets/lv_arc.c \
Drivers/lvgl/src/widgets/lv_bar.c \
Drivers/lvgl/src/widgets/lv_btn.c \
Drivers/lvgl/src/widgets/lv_btnmatrix.c \
Drivers/lvgl/src/widgets/lv_canvas.c \
Drivers/lvgl/src/widgets/lv_checkbox.c \
Drivers/lvgl/src/widgets/lv_dropdown.c \
Drivers/lvgl/src/widgets/lv_img.c \
Drivers/lvgl/src/widgets/lv_label.c \
Drivers/lvgl/src/widgets/lv_line.c \
Drivers/lvgl/src/widgets/lv_objx_templ.c \
Drivers/lvgl/src/widgets/lv_roller.c \
Drivers/lvgl/src/widgets/lv_slider.c \
Drivers/lvgl/src/widgets/lv_switch.c \
Drivers/lvgl/src/widgets/lv_table.c \
Drivers/lvgl/src/widgets/lv_textarea.c \
Drivers/lvgl/tests/makefile/test.c \
Drivers/lvgl/tests/src/lv_test_indev.c \
Drivers/lvgl/tests/src/lv_test_init.c \
Drivers/lvgl/tests/src/test_cases/_test_template.c \
Drivers/lvgl/tests/src/test_cases/test_arc.c \
Drivers/lvgl/tests/src/test_cases/test_bar.c \
Drivers/lvgl/tests/src/test_cases/test_checkbox.c \
Drivers/lvgl/tests/src/test_cases/test_config.c \
Drivers/lvgl/tests/src/test_cases/test_demo_stress.c \
Drivers/lvgl/tests/src/test_cases/test_demo_widgets.c \
Drivers/lvgl/tests/src/test_cases/test_dropdown.c \
Drivers/lvgl/tests/src/test_cases/test_event.c \
Drivers/lvgl/tests/src/test_cases/test_font_loader.c \
Drivers/lvgl/tests/src/test_cases/test_fs.c \
Drivers/lvgl/tests/src/test_cases/test_line.c \
Drivers/lvgl/tests/src/test_cases/test_mem.c \
Drivers/lvgl/tests/src/test_cases/test_obj_tree.c \
Drivers/lvgl/tests/src/test_cases/test_slider.c \
Drivers/lvgl/tests/src/test_cases/test_snapshot.c \
Drivers/lvgl/tests/src/test_cases/test_style.c \
Drivers/lvgl/tests/src/test_cases/test_switch.c \
Drivers/lvgl/tests/src/test_cases/test_table.c \
Drivers/lvgl/tests/src/test_cases/test_textarea.c \
Drivers/lvgl/tests/src/test_cases/test_tiny_ttf.c \
Drivers/lvgl/tests/src/test_cases/test_txt.c \
Drivers/lvgl/tests/src/test_fonts/font_1.c \
Drivers/lvgl/tests/src/test_fonts/font_2.c \
Drivers/lvgl/tests/src/test_fonts/font_3.c \
Drivers/lvgl/tests/src/test_fonts/ubuntu_font.c \
Drivers/lvgl/tests/unity/unity.c \
Drivers/lvgl/tests/unity/unity_support.c \
Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src/usbh_cdc.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c \
Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c


CXX_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s


#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
    DP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objdump$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
  DP ?= $(ARM_PREFIX)objdump
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
LSS = $(DP) -h -S


REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c if not exist $(call convert_to_windows_path,$(1)) md $(call convert_to_windows_path,$(1))
endif


# Flash and debug tools
# Default is openocd however will be gotten from the env file when existing
OPENOCD ?= openocd


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F407xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F407xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Inc/Config \
-IDrivers/BSP/Components/Common \
-IDrivers/BSP/Components/cs43l22 \
-IDrivers/BSP/Components/lis302dl \
-IDrivers/BSP/Components/lis3dsh \
-IDrivers/BSP/STM32F4-Discovery \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/ST7789V \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/lvgl \
-IDrivers/lvgl/demos \
-IDrivers/lvgl/demos/benchmark \
-IDrivers/lvgl/demos/keypad_encoder \
-IDrivers/lvgl/demos/music \
-IDrivers/lvgl/demos/music/assets \
-IDrivers/lvgl/demos/stress \
-IDrivers/lvgl/demos/widgets \
-IDrivers/lvgl/env_support/cmsis-pack \
-IDrivers/lvgl/env_support/rt-thread \
-IDrivers/lvgl/env_support/rt-thread/squareline/ui/lvgl \
-IDrivers/lvgl/src \
-IDrivers/lvgl/src/core \
-IDrivers/lvgl/src/draw \
-IDrivers/lvgl/src/draw/arm2d \
-IDrivers/lvgl/src/draw/nxp/pxp \
-IDrivers/lvgl/src/draw/nxp/vglite \
-IDrivers/lvgl/src/draw/renesas \
-IDrivers/lvgl/src/draw/sdl \
-IDrivers/lvgl/src/draw/stm32_dma2d \
-IDrivers/lvgl/src/draw/sw \
-IDrivers/lvgl/src/draw/swm341_dma2d \
-IDrivers/lvgl/src/extra \
-IDrivers/lvgl/src/extra/layouts \
-IDrivers/lvgl/src/extra/layouts/flex \
-IDrivers/lvgl/src/extra/layouts/grid \
-IDrivers/lvgl/src/extra/libs \
-IDrivers/lvgl/src/extra/libs/bmp \
-IDrivers/lvgl/src/extra/libs/ffmpeg \
-IDrivers/lvgl/src/extra/libs/freetype \
-IDrivers/lvgl/src/extra/libs/fsdrv \
-IDrivers/lvgl/src/extra/libs/gif \
-IDrivers/lvgl/src/extra/libs/png \
-IDrivers/lvgl/src/extra/libs/qrcode \
-IDrivers/lvgl/src/extra/libs/rlottie \
-IDrivers/lvgl/src/extra/libs/sjpg \
-IDrivers/lvgl/src/extra/libs/tiny_ttf \
-IDrivers/lvgl/src/extra/others \
-IDrivers/lvgl/src/extra/others/fragment \
-IDrivers/lvgl/src/extra/others/gridnav \
-IDrivers/lvgl/src/extra/others/ime \
-IDrivers/lvgl/src/extra/others/imgfont \
-IDrivers/lvgl/src/extra/others/monkey \
-IDrivers/lvgl/src/extra/others/msg \
-IDrivers/lvgl/src/extra/others/snapshot \
-IDrivers/lvgl/src/extra/themes \
-IDrivers/lvgl/src/extra/themes/basic \
-IDrivers/lvgl/src/extra/themes/default \
-IDrivers/lvgl/src/extra/themes/mono \
-IDrivers/lvgl/src/extra/widgets \
-IDrivers/lvgl/src/extra/widgets/animimg \
-IDrivers/lvgl/src/extra/widgets/calendar \
-IDrivers/lvgl/src/extra/widgets/chart \
-IDrivers/lvgl/src/extra/widgets/colorwheel \
-IDrivers/lvgl/src/extra/widgets/imgbtn \
-IDrivers/lvgl/src/extra/widgets/keyboard \
-IDrivers/lvgl/src/extra/widgets/led \
-IDrivers/lvgl/src/extra/widgets/list \
-IDrivers/lvgl/src/extra/widgets/menu \
-IDrivers/lvgl/src/extra/widgets/meter \
-IDrivers/lvgl/src/extra/widgets/msgbox \
-IDrivers/lvgl/src/extra/widgets/span \
-IDrivers/lvgl/src/extra/widgets/spinbox \
-IDrivers/lvgl/src/extra/widgets/spinner \
-IDrivers/lvgl/src/extra/widgets/tabview \
-IDrivers/lvgl/src/extra/widgets/tileview \
-IDrivers/lvgl/src/extra/widgets/win \
-IDrivers/lvgl/src/font \
-IDrivers/lvgl/src/hal \
-IDrivers/lvgl/src/misc \
-IDrivers/lvgl/src/widgets \
-IDrivers/lvgl/tests/src \
-IDrivers/lvgl/tests/unity \
-IMiddlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc \
-IMiddlewares/ST/STM32_USB_Host_Library/Core/Inc \
-IUSB_HOST/App \
-IUSB_HOST/Target



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(C_INCLUDES) $(C_DEFS) $(OPTIMIZATION_FLAGS) 

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPTIMIZATION_FLAGS)

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)
CFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)
CXXFLAGS += $(ASSEMBLER_LIST_OUTPUT_FLAG)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIRECTORY)/$(TARGET).map,--cref -Wl,--gc-sections

#######################################
# build the application
#######################################
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(addsuffix .$(2),$(basename $(notdir $(1))))))



OBJECTS = $(call add_release_directory,$(C_SOURCES),o)
OBJECTS += $(call add_release_directory,$(CXX_SOURCES),o)
OBJECTS += $(call add_release_directory,$(ASM_SOURCES),o)
vpath %.c $(sort $(dir $(C_SOURCES)))
vpath %.cc $(sort $(dir $(CXX_SOURCES)))
vpath %.cp $(sort $(dir $(CXX_SOURCES)))
vpath %.cxx $(sort $(dir $(CXX_SOURCES)))
vpath %.cpp $(sort $(dir $(CXX_SOURCES)))
vpath %.c++ $(sort $(dir $(CXX_SOURCES)))
vpath %.C $(sort $(dir $(CXX_SOURCES)))
vpath %.CPP $(sort $(dir $(CXX_SOURCES)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

#######################################
# all
#######################################
# note needs to be located as the first rule to be the default build rule
# default action: build all
all: $(RELEASE_DIRECTORY)/$(TARGET).elf $(RELEASE_DIRECTORY)/$(TARGET).hex $(RELEASE_DIRECTORY)/$(TARGET).bin $(RELEASE_DIRECTORY)/$(TARGET).lss 


# C build
$(RELEASE_DIRECTORY)/%.o: %.c STM32Make.make | $(RELEASE_DIRECTORY)
	$(CC) -c $(CFLAGS) $< -o $@

# C++ build 
$(RELEASE_DIRECTORY)/%.o: %.cc STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cxx STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.cpp STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.c++ STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.C STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.CPP STM32Make.make | $(RELEASE_DIRECTORY)
	$(CXX) -c $(CXXFLAGS) $< -o $@

#Assembly build
$(RELEASE_DIRECTORY)/%.o: %.s STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.S STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/%.o: %.sx STM32Make.make | $(RELEASE_DIRECTORY)
	$(AS) -c $(ASFLAGS) $< -o $@

$(RELEASE_DIRECTORY)/$(TARGET).elf: $(OBJECTS) STM32Make.make | $(RELEASE_DIRECTORY)
	@echo $(OBJECTS) > $@.in
	$(CC) @$@.in $(LDFLAGS) -o $@
	$(SZ) $@

$(RELEASE_DIRECTORY)/%.hex: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(HEX) $< $@

$(RELEASE_DIRECTORY)/%.bin: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(BIN) $< $@

$(RELEASE_DIRECTORY)/%.lss: $(RELEASE_DIRECTORY)/%.elf | $(RELEASE_DIRECTORY)
	$(LSS) $< > $@

$(RELEASE_DIRECTORY):
	$(call mkdir_function, $@)

$(BUILD_DIRECTORY): | $(RELEASE_DIRECTORY)
	$(call mkdir_function, $@)


#######################################
# flash
#######################################
flash: all
	"$(OPENOCD)" -f ./openocd.cfg -c "program $(RELEASE_DIRECTORY)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: all
	"$(OPENOCD)" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################

	
#######################################
# dependencies
#######################################
-include $(wildcard $(RELEASE_DIRECTORY)/*.d)

# *** EOF ***